# Usa uma imagem leve do servidor Nginx
FROM nginx:alpine

# Copia seus arquivos HTML/CSS/JS para a pasta pública do Nginx
COPY . /usr/share/nginx/html

# O Nginx roda na porta 80 por padrão
EXPOSE 80